version: "2"
services:
    # MySQL 5.7: https://hub.docker.com/_/mysql/
    mysql:
        container_name: mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "test123"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "test123"
            MYSQL_DATABASE: "one"
        volumes:
            - /home/docker/mysql:/var/lib/mysql
        ports:
            - "13306:3306"

    # Redis 3.2.10: https://hub.docker.com/_/redis/
    redis:
        container_name: redis
        image: redis:3.2.10
        volumes:
            - /home/docker/redis:/data
        ports:
            - "16379:6379"
    # Nginx 1.13.: https://hub.docker.com/_/nginx/
    web:
        container_name: web
        image: nginx:latest
        restart: always
        network_mode: "bridge"
        volumes:
            - /var/www/html/web:/home/web
        ports:
            - "9999:80"

    #架阿里云内网  registry-internal.cn-hangzhou.aliyuncs.com/peterpang/web
    peter:
        container_name: peter
        image:  registry-internal.cn-hangzhou.aliyuncs.com/peterpang/web
        links:
            - mysql
            - redis
            - web
        volumes:
            - /home/docker_user/peter:/home
        ports: 
            - "10181:8081"
            - "10183:8083"
            - "10193:9093"
            - "10122:22"

    ljj:
        container_name: ljj
        image:  registry-internal.cn-hangzhou.aliyuncs.com/peterpang/web
        links:
            - mysql
            - redis
            - web
        volumes:
            - /home/docker_user/ljj:/home
        ports:
            - "10281:8081"
            - "10283:8083"
            - "10293:9093"
            - "10222:22"

    hy:
            container_name: hy
            image:  registry-internal.cn-hangzhou.aliyuncs.com/peterpang/web
            links:
                - mysql
                - redis
                - web
            volumes:
                - /home/docker_user/hy:/home
            ports:
                - "10381:8081"
                - "10383:8083"
                - "10393:9093"
                - "10322:22"
                
    jm:
            container_name: jm
            image:  registry-internal.cn-hangzhou.aliyuncs.com/peterpang/web
            links:
                - mysql
                - redis
                - web
            volumes:
                - /home/docker_user/jm:/home
            ports:
                - "10481:8081"
                - "10483:8083"
                - "10493:9093"
                - "10422:22"
    joseph:
            container_name: joseph
            image:  registry-internal.cn-hangzhou.aliyuncs.com/peterpang/web
            links:
                - mysql
                - redis
                - web
            volumes:
                - /home/docker_user/joseph:/home
            ports:
                - "10581:8081"
                - "10583:8083"
                - "10593:9093"
                - "10522:22"